name: asood
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"



dependencies:
  bloc: ^9.0.0
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.2.1
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_otp_text_field: ^1.1.1
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.9
  geolocator: ^10.1.0  
  http: ^1.2.0
  image_picker: ^1.1.2
  intl: any
  intl_phone_field: ^3.2.0
  latlong2: ^0.9.0
  location: ^6.0.2
  vector_graphics: ^1.1.18
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^14.8.1
  dio: ^5.8.0+1
  get_it: ^8.0.3




dev_dependencies:
  build_runner: any
  flutter_lints: ^5.0.0
  analyzer: ^6.11.0
  hive_generator: ^2.0.0

flutter_gen:
  output: lib/core/gen/
  line_length: 80 

  integrations:
    image: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: irs
      fonts:
        - asset: assets/fonts/irs.ttf
    - family: yekan
      fonts:
        - asset: assets/fonts/yekan.ttf
    - family: dastnevis
      fonts:
        - asset: assets/fonts/dastnevis.otf
    - family: mitra
      fonts:
        - asset: assets/fonts/mitra.ttf
    - family: nazanin
      fonts:
        - asset: assets/fonts/nazanin.ttf
    - family: traffic
      fonts:
        - asset: assets/fonts/traffic.ttf